### PR TITLE
State initially submitted to cran as 0.4.0

### PR DESCRIPTION
**Pull request by gmbecker**
[skip vbump]

### CODE REVIEW

**Comment by gmbecker** [comment]
We are going to have to just ride out the spell check failure for this release, as the package has already been submitted (there are only 2 words, both in the NEWS.md file)

**Comment by shajoezhu** [comment]
Hi @gmbecker , I was wondering why we can't fix it here. and then submit to cran? have you submitted already? then updating the file here?

**Comment by gmbecker** [comment]
> Hi @gmbecker , I was wondering why we can't fix it here. and then submit to cran? have you submitted already? then updating the file here?

Yes, I have submitted already.

**Comment by shajoezhu** [comment]
Hi @gmbecker , i think it's ok to fix the spelling here and merge it into main. since it is already on cran

**Pull request closed without merging**
