### PR TITLE
447 remove formatters from teal packages

### PR DESCRIPTION
**Pull request by m7pr**
A consequence of https://github.com/insightsengineering/coredev-tasks/issues/447

### CODE REVIEW

**Review by edelarua — APPROVED** [review]
Lgtm!

**Comment by shajoezhu** [comment]
hi @m7pr and @edelarua , thanks a lot for the work. just want to hold this PR for one more day after making the release tag. thanks

**Comment by m7pr** [comment]
Hey, depending on the outcome of cards for `teal` packages that are dependent on `tern`, which imports `formatters` (hence are not crucial) we may need to keep `teal.modules.clinical` and `teal.osprey` in the `staged.dependencies.yml` file

https://github.com/insightsengineering/teal.modules.clinical/issues/794
https://github.com/insightsengineering/teal.osprey/issues/219

**Comment by shajoezhu** [comment]
hey @m7pr , that sounds good. please update the PR accordingly. Thanks in advance!

**Comment by m7pr** [comment]
Hey @shajoezhu and @edelarua - I did update the PR so that we keep teal.osprey and teal.modules.clinical. Pleas take one more review and accept

**Review by shajoezhu — APPROVED** [review]
lgtm! Thanks @m7pr

**Pull request merged**
