### PR TITLE
Add code of conduct 

### PR DESCRIPTION
**Pull request by martincadek**
Closes https://github.com/insightsengineering/formatters/issues/238

### CODE REVIEW

**Review by shajoezhu — CHANGES_REQUESTED** [review]
hi @martincadek , thanks for the PR, the lintr check is failing, can you please resolve that. thanks!

https://github.com/insightsengineering/formatters/actions/runs/8286491619/job/22676608465

**Review by martincadek — COMMENTED** [review]
fix: barebone URL and missing single traling newline

**Comment by martincadek** [comment]
Thansk for the notices @shajoezhu Changes submited, checks passed.

**Review by shajoezhu — APPROVED** [review]
lgtm! thanks @martincadek

**Comment by shajoezhu** [comment]
> hi @martincadek , thanks for the PR, the lintr check is failing, can you please resolve that. thanks!
> 
> https://github.com/insightsengineering/formatters/actions/runs/8286491619/job/22676608465

hi @cicdguy and @walkowif , I was a bit puzzled with this failed check for lintr, this was a direct copy from rtables, but it never failed on the rtables side,  and it was picked up here.

**Pull request merged**
